title: Jekyll Experiment
author: dbattice
email: your_not_getting_this@github.io
description: > # this means to ignore newlines until "baseurl:"
  I have no idea what I am doing. Yet.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
